# Generated by Django 5.0.7 on 2024-08-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
